services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_server
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/servidor
    working_dir: /servidor
    command: uvicorn main:app --host 0.0.0.0 --reload
    restart: on-failure

  frontend:
    depends_on:
      - backend
    build:
      context: ./interface
      dockerfile: Dockerfile
    container_name: interface_app
    ports:
      - "5173:5173"
    volumes:
      - ./interface:/app
      - /app/node_modules
    environment:
      - VITE_YOUTUBE_API_KEY=${VITE_YOUTUBE_API_KEY}
    working_dir: /app
    command: npm run dev -- --host
    restart: on-failure
